create database booksystem;

use booksystem;

select * from books;
select * from customers;
select * from orders;

-- 1.All books in the "Fiction" genre
select * from books
where Genre = 'Fiction';

-- 2.Find books published after year 1950
select * from books 
where Published_Year > '1950';

-- 3.List all customers from the Canada
select * from customers
where Country = 'Canada';

-- 4.Show order placed in nov 2023--
select * from orders
where month(Order_Date) = '11' and year(Order_Date) = '2023';

-- 5.Retrive the total stock from books available--
select count(*) from books;

-- 6.Find the details of most expensive books
select Book_Id, max(price) from books
group by Book_Id
order by max(price) desc;

-- 7.Show all customer who ordered more than 1 quantity of books
select * from customers c 
join orders o on c.Customer_ID = o.Customer_ID
where  o.Quantity > 1;


-- 8.list all orders where total amount exceeds $20
select * from orders
where Total_Amount > 100;

-- 9.list all genre avilable in the books
select Genre,count(Genre) from books
group by Genre;

-- 10.Find the book with the lowest stock
select Title,min(stock) as Min_stock from books
group by Title 
order by Min_stock asc limit 5;

-- 11.Calculate total revenue generated by all orders--
select sum(b.Price * o.Quantity) as Total_revenue from orders o 
join books b on o.Book_ID = b.Book_ID; 

-- 12.Retrive the total no of books sold by each genre--
SELECT b.Genre, SUM(o.Quantity) AS Total_Books_sold
FROM Orders o
JOIN Books b ON o.book_id = b.book_id
GROUP BY b.Genre;

-- 13.Find average price of books in the Fantacy genre
select round(avg(Price),2) from books 
where genre = 'Fantasy';

-- 14.List cust who have placed at least 2 orders
select c.customer_id,c.name, count(o.order_id) as no_orders from customers c 
join orders o on c.customer_id = o.customer_id
group by c.customer_id,c.name
having  no_orders = 2;

-- 15.Find the most frequntly orders book
select book_id ,count(*) as most_frequently from orders
group by book_id
order by most_frequently desc limit 1;

-- 16.Show the most top 3 most expensive books of fantacy genre
select title,max(price) as most_expensive from books 
where genre = 'Fantasy'
group by title
order by most_expensive desc limit 3;

-- 17.Retrive the  total quentity of books sold by each author
select b.author, sum(o.Quantity) as sold from books b 
join orders o on b.book_id = o.book_id
group by b.author;

-- 18.List all cities where customer spend over $30 are located 
select distinct c.city,o.total_amount  from orders o
join customers c on o.customer_id = c.customer_id 
where o.total_amount > 30; 

-- 19.Find the customer who spend most orders
select c.name ,sum(o.total_amount) as most_orders from customers c
join orders o on c.customer_id = o.customer_id 
group by c.name
order by most_orders desc limit 1;

-- 20.Calculate the stock remaining after all orders 
SELECT b.book_id, b.title, b.stock, COALESCE(SUM(o.quantity),0) AS Order_quantity,  
	b.stock - COALESCE(SUM(o.quantity),0) AS Remaining_Quantity
FROM books b
LEFT JOIN orders o ON b.book_id=o.book_id
GROUP BY b.book_id, b.title, b.stock
ORDER BY b.book_id;